version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase

  redis:
    container_name: redis
    image: redis

  app:
    container_name: app
    build: "./app"
    environment:
      REDIS_HOST: redis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    command: ["npm", "start"]
    depends_on:
      - "redis"
      - "postgres"

  nginx:
    container_name: nginx
    build: "./nginx"
    ports:
      - "80:80"
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - "app"
