version: "3.8"

services:
  database:
    container_name: database
    build:
      context: ./database/
    networks:
      - backend_network

  backend:
    container_name: backend
    build:
      context: ./backend/
    networks:
      - frontend_network
      - backend_network

  frontend:
    container_name: frontend
    build:
      context: ./frontend/
    ports:
      - 8080:80
    networks:
      - frontend_network

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge
